name: Create PR to Main Branch

on:
  push:
    branches:
      - sqa

jobs:
  create-main-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for peter-evans/create-pull-request

    - name: Create Pull Request to Main
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Automated: PR from sqa to main'
        title: 'Automated PR: SQA Approved changes for Production deployment'
        body: |
          This is an automated pull request from the `sqa` branch to the `main` branch.
          SQA has approved these changes. Please review and approve for deployment to production.
        head: sqa
        base: main
        branch: automated-pr-to-main-${{ github.run_id }}
        delete-branch: true
