name: Unit Tests on Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven tests
      run: mvn -B test --file pom.xml
